export const PROPERTY_TYPES = ["Terreno", "Casa", "Loja comercial", "Apartamento", "Apartamento duplex", "Fazenda", "Chácara"];
export const LOCATIONS = [
  "Água Quente, Distrito Federal, Brasília",
  "Águas Claras, Distrito Federal, Brasília",
  "Arapoanga, Distrito Federal, Brasília",
  "Arniqueira, Distrito Federal, Brasília",
  "Brazlândia, Distrito Federal, Brasília",
  "Candangolândia, Distrito Federal, Brasília",
  "Ceilândia, Distrito Federal, Brasília",
  "Cruzeiro, Distrito Federal, Brasília",
  "Fercal, Distrito Federal, Brasília",
  "Gama, Distrito Federal, Brasília",
  "Grande Colorado, Distrito Federal, Brasília",
  "Guará, Distrito Federal, Brasília",
  "Itapoã, Distrito Federal, Brasília",
  "Jardim Botânico, Distrito Federal, Brasília",
  "Lago Norte, Distrito Federal, Brasília",
  "Lago Sul, Distrito Federal, Brasília",
  "Núcleo Bandeirante, Distrito Federal, Brasília",
  "Paranoá, Distrito Federal, Brasília",
  "Park Way, Distrito Federal, Brasília",
  "Planaltina, Distrito Federal, Brasília",
  "Plano Piloto, Distrito Federal, Brasília",
  "Recanto das Emas, Distrito Federal, Brasília",
  "Riacho Fundo, Distrito Federal, Brasília",
  "Riacho Fundo II, Distrito Federal, Brasília",
  "Samambaia, Distrito Federal, Brasília",
  "Santa Maria, Distrito Federal, Brasília",
  "São Sebastião, Distrito Federal, Brasília",
  "Setor de Mansões, Distrito Federal, Brasília",
  "SCIA (Estrutural), Distrito Federal, Brasília",
  "SIA, Distrito Federal, Brasília",
  "Sobradinho, Distrito Federal, Brasília",
  "Sobradinho II, Distrito Federal, Brasília",
  "Sol Nascente e Pôr do Sol, Distrito Federal, Brasília",
  "Sudoeste/Octogonal, Distrito Federal, Brasília",
  "Taguatinga, Distrito Federal, Brasília",
  "Varjão, Distrito Federal, Brasília",
  "Vicente Pires, Distrito Federal, Brasília",
  "Águas Lindas de Goiás, Goiás",
];
export const money = (value:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value);
